/**
 * autoPlaylistGenerator.js
 *
 * Generates playlist metadata objects from a list of songs that have
 * been scanned from the filesystem. Each unique folderName becomes a
 * separate auto-generated playlist.
 */

/**
 * Given an array of song objects (each with a `folderName` property),
 * returns an array of playlist objects ready to be saved to IndexedDB.
 *
 * @param {Array<{id: number, folderName: string, [key: string]: any}>} songs
 * @returns {Array<{name: string, songs: number[], isAutoGenerated: boolean, source: string, createdAt: Date}>}
 */
export function generatePlaylistsFromFolders(songs) {
    /** @type {Map<string, { name: string, songs: number[], isAutoGenerated: boolean, source: string, createdAt: Date }>} */
    const playlistMap = new Map();

    for (const song of songs) {
        const folderName = song.folderName?.trim() || 'Uncategorized';

        if (!playlistMap.has(folderName)) {
            playlistMap.set(folderName, {
                name: folderName,
                description: `Auto-generated from folder: ${folderName}`,
                songs: [],
                isAutoGenerated: true,
                source: 'folder',
                createdAt: new Date(),
            });
        }

        // song.id may be undefined until persisted; callers should pass
        // songs that already have IDs assigned by IndexedDB.
        if (song.id !== undefined) {
            playlistMap.get(folderName).songs.push(song.id);
        }
    }

    return Array.from(playlistMap.values());
}

/**
 * Merge a freshly-generated playlist list with the existing playlists
 * already stored in the DB.  Auto-generated playlists that no longer
 * have a matching folder are removed; new ones are added; existing ones
 * get their song lists refreshed.
 *
 * Returns three arrays that the caller can use to drive DB writes:
 *   - `toAdd`    – brand-new auto playlists (call db.playlists.add)
 *   - `toUpdate` – existing auto playlists with updated song arrays (call db.playlists.put)
 *   - `toDelete` – stale auto playlists that no longer exist (call db.playlists.delete)
 *
 * @param {Array} freshPlaylists  – output of generatePlaylistsFromFolders()
 * @param {Array} existingPlaylists – current db.playlists.toArray() result
 */
export function diffAutoPlaylists(freshPlaylists, existingPlaylists) {
    const existingAuto = existingPlaylists.filter(p => p.isAutoGenerated);
    const existingMap = new Map(existingAuto.map(p => [p.name, p]));
    const freshNames = new Set(freshPlaylists.map(p => p.name));

    const toAdd = [];
    const toUpdate = [];
    const toDelete = [];

    for (const fresh of freshPlaylists) {
        if (existingMap.has(fresh.name)) {
            // Update song list on existing playlist
            const existing = existingMap.get(fresh.name);
            toUpdate.push({ ...existing, songs: fresh.songs });
        } else {
            toAdd.push(fresh);
        }
    }

    for (const existing of existingAuto) {
        if (!freshNames.has(existing.name)) {
            toDelete.push(existing.id);
        }
    }

    return { toAdd, toUpdate, toDelete };
}
