import Dexie from 'dexie';

export const db = new Dexie('SmartMusicPlayer');

// Version 1 — original songs + audioFiles (blobs)
db.version(1).stores({
    songs: '++id, title, artist, album, genre, dateAdded',
    audioFiles: '++id, songId, blob',
});

// Version 2 — added playlists
db.version(2).stores({
    songs: '++id, title, artist, album, genre, dateAdded',
    audioFiles: '++id, songId, blob',
    playlists: '++id, name, createdAt',
});

// Version 3 — Folder-scanning migration
//   • fileHandles: maps filePath → FileSystemFileHandle
//   • folderHandle: single row storing the root folder handle
//   • audioFiles table is kept (for legacy blob-uploaded songs)
db.version(3).stores({
    songs:       '++id, title, artist, album, genre, dateAdded, filePath, sourceType',
    audioFiles:  '++id, songId, blob',
    playlists:   '++id, name, createdAt, isAutoGenerated',
    fileHandles: 'filePath',          // keyed by filePath, stores { filePath, handle }
    folderHandle: 'id',               // single row: { id: "music-folder", handle, grantedAt }
});

// ─── Legacy blob helpers (still used by old uploaded songs) ────────────────

export async function saveSongWithAudio(songData, audioBlob) {
    try {
        const songId = await db.songs.add({ ...songData, sourceType: 'upload' });
        await db.audioFiles.add({ songId, blob: audioBlob });
        return songId;
    } catch (error) {
        console.error('Error saving song:', error);
        throw error;
    }
}

export async function getAudioBlob(songId) {
    try {
        const audioFile = await db.audioFiles
            .where('songId')
            .equals(songId)
            .first();
        return audioFile?.blob;
    } catch (error) {
        console.error('Error getting audio blob:', error);
        return null;
    }
}

// ─── Folder handle helpers ──────────────────────────────────────────────────

/**
 * Persist the root folder handle so we can re-access it on future visits.
 */
export async function storeFolderHandle(dirHandle) {
    await db.folderHandle.put({
        id: 'music-folder',
        handle: dirHandle,
        grantedAt: new Date(),
    });
}

/**
 * Retrieve the stored folder handle and verify/re-request permission.
 * Returns the handle if accessible, or null if not set / permission denied.
 */
export async function getFolderHandle() {
    try {
        const record = await db.folderHandle.get('music-folder');
        if (!record) return null;

        const permission = await record.handle.queryPermission({ mode: 'read' });

        if (permission === 'granted') {
            return record.handle;
        }

        // Permission was revoked — ask again (requires user gesture)
        const newPermission = await record.handle.requestPermission({ mode: 'read' });
        return newPermission === 'granted' ? record.handle : null;
    } catch (err) {
        console.warn('[indexedDB] Could not get folder handle:', err);
        return null;
    }
}

/**
 * Silently check if the stored folder handle still has read permission.
 * Unlike getFolderHandle(), this NEVER calls requestPermission (which
 * requires a user gesture and would throw if called on page load).
 *
 * Returns: 'granted' | 'prompt' | 'denied' | null (no handle stored)
 */
export async function checkFolderPermission() {
    try {
        const record = await db.folderHandle.get('music-folder');
        if (!record) return null;
        return await record.handle.queryPermission({ mode: 'read' });
    } catch {
        return 'prompt'; // Assume needs permission on any error
    }
}

/**
 * Remove the stored folder handle (e.g. when user wants to change folder).
 */
export async function clearFolderHandle() {
    await db.folderHandle.delete('music-folder');
}

// ─── Per-file handle helpers ────────────────────────────────────────────────

/**
 * Store the FileSystemFileHandle for a song identified by its filePath.
 */
export async function storeFileHandle(filePath, fileHandle) {
    await db.fileHandles.put({ filePath, handle: fileHandle });
}

/**
 * Get a File object from the stored handle for the given filePath.
 * Returns null if not found or file is no longer accessible.
 */
export async function getAudioFile(filePath) {
    try {
        const record = await db.fileHandles.get(filePath);
        if (!record) return null;
        return await record.handle.getFile();
    } catch (error) {
        console.error('[indexedDB] Error accessing file handle:', error);
        return null;
    }
}

/**
 * Delete the file handle for a given filePath (called when removing a song).
 */
export async function deleteFileHandle(filePath) {
    await db.fileHandles.delete(filePath);
}
