import { create } from 'zustand';
import { db } from '../lib/db/indexedDB';
import {
    generatePlaylistsFromFolders,
    diffAutoPlaylists,
} from '../lib/playlists/autoPlaylistGenerator';

export const usePlaylistStore = create((set, get) => ({
    playlists: [],
    isLoading: false,

    // ─── Fetch ───────────────────────────────────────────────────────────────

    fetchPlaylists: async () => {
        set({ isLoading: true });
        try {
            const playlists = await db.playlists.toArray();
            set({ playlists, isLoading: false });
        } catch (error) {
            console.error('Error fetching playlists:', error);
            set({ isLoading: false });
        }
    },

    // ─── User-created playlist ────────────────────────────────────────────────

    /**
     * Create a new manually-curated playlist.
     * Sets isAutoGenerated: false so it's never overwritten by folder scans.
     */
    createPlaylist: async (name, description = '') => {
        try {
            const playlist = {
                name,
                description,
                songs: [],
                isAutoGenerated: false,
                createdAt: new Date(),
            };
            const id = await db.playlists.add(playlist);
            const newPlaylist = { ...playlist, id };
            set((state) => ({ playlists: [...state.playlists, newPlaylist] }));
            return newPlaylist;
        } catch (error) {
            console.error('Error creating playlist:', error);
            throw error;
        }
    },

    // ─── Auto-playlist generation (Phase 2) ──────────────────────────────────

    /**
     * Called after a full folder scan.
     * Accepts songs that ALREADY HAVE IndexedDB `id` values assigned.
     *
     * 1. Generates playlist objects grouped by folderName.
     * 2. Diffs against existing auto-playlists in the DB.
     * 3. Writes adds/updates/deletes to IndexedDB.
     * 4. Updates the Zustand store with the final playlist list.
     */
    generateFromFolders: async (songs) => {
        try {
            const freshPlaylists = generatePlaylistsFromFolders(songs);
            const existingPlaylists = await db.playlists.toArray();

            const { toAdd, toUpdate, toDelete } = diffAutoPlaylists(
                freshPlaylists,
                existingPlaylists,
            );

            // Persist changes
            for (const playlist of toAdd) {
                const id = await db.playlists.add(playlist);
                playlist.id = id;
            }
            for (const playlist of toUpdate) {
                await db.playlists.put(playlist);
            }
            for (const id of toDelete) {
                await db.playlists.delete(id);
            }

            // Rebuild in-memory list from DB to stay in sync
            const updatedPlaylists = await db.playlists.toArray();
            set({ playlists: updatedPlaylists });

            console.log(
                `[PlaylistStore] Auto-playlists: +${toAdd.length} added, ` +
                `~${toUpdate.length} updated, -${toDelete.length} removed`,
            );

            return { added: toAdd.length, updated: toUpdate.length, removed: toDelete.length };
        } catch (error) {
            console.error('[PlaylistStore] Error generating playlists from folders:', error);
            throw error;
        }
    },

    // ─── Song management within playlists ────────────────────────────────────

    /**
     * Add a song to a playlist (by ID).
     */
    addSongToPlaylist: async (playlistId, songId) => {
        try {
            const playlist = await db.playlists.get(playlistId);
            if (!playlist) throw new Error('Playlist not found');

            if (playlist.songs.includes(songId)) return; // already in playlist

            const updated = { ...playlist, songs: [...playlist.songs, songId] };
            await db.playlists.put(updated);

            set((state) => ({
                playlists: state.playlists.map((p) =>
                    p.id === playlistId ? updated : p,
                ),
            }));
        } catch (error) {
            console.error('[PlaylistStore] Error adding song to playlist:', error);
            throw error;
        }
    },

    /**
     * Remove a song from a playlist (by ID).
     */
    removeSongFromPlaylist: async (playlistId, songId) => {
        try {
            const playlist = await db.playlists.get(playlistId);
            if (!playlist) throw new Error('Playlist not found');

            const updated = {
                ...playlist,
                songs: playlist.songs.filter((id) => id !== songId),
            };
            await db.playlists.put(updated);

            set((state) => ({
                playlists: state.playlists.map((p) =>
                    p.id === playlistId ? updated : p,
                ),
            }));
        } catch (error) {
            console.error('[PlaylistStore] Error removing song from playlist:', error);
            throw error;
        }
    },

    /**
     * Delete a playlist entirely.
     * Auto-generated playlists can be deleted too (they'll be re-created on next scan).
     */
    deletePlaylist: async (playlistId) => {
        try {
            await db.playlists.delete(playlistId);
            set((state) => ({
                playlists: state.playlists.filter((p) => p.id !== playlistId),
            }));
        } catch (error) {
            console.error('[PlaylistStore] Error deleting playlist:', error);
            throw error;
        }
    },

    // ─── Computed helpers ─────────────────────────────────────────────────────

    /** Returns only the auto-generated (folder-derived) playlists. */
    getAutoPlaylists: () => get().playlists.filter((p) => p.isAutoGenerated),

    /** Returns only user-created playlists. */
    getUserPlaylists: () => get().playlists.filter((p) => !p.isAutoGenerated),
}));