import { useState } from 'react';
import { FolderOpen, Music2, Shield, Zap, HardDrive } from 'lucide-react';
import { useLibraryStore } from '../../store/store';
import { storeFolderHandle, storeFileHandle, db } from '../../lib/db/indexedDB';
import { scanMusicFolder } from '../../lib/filesystem/folderScanner';

export default function FolderSetupScreen({ onComplete }) {
    const fetchSongs     = useLibraryStore((s) => s.fetchSongs);
    const fetchPlaylists = useLibraryStore((s) => s.fetchPlaylists);

    const [phase, setPhase]       = useState('idle');
    const [scanned, setScanned]   = useState(0);
    const [lastName, setLastName] = useState('');
    const [error, setError]       = useState(null);

    const isSupported = typeof window !== 'undefined' && 'showDirectoryPicker' in window;

    const handleSelectFolder = async () => {
        if (!isSupported) return;
        setError(null);
        try {
            const dirHandle = await window.showDirectoryPicker({ mode: 'read' });
            await storeFolderHandle(dirHandle);
            setPhase('scanning');
            setScanned(0);

            const { songs } = await scanMusicFolder(dirHandle, (count, name) => {
                setScanned(count);
                setLastName(name);
            });

            const existingTitles = new Set();
            for (const song of songs) {
                const titleKey = song.title?.toLowerCase().trim();
                if (existingTitles.has(titleKey)) continue;
                const { fileHandle, ...songData } = song;
                await db.songs.add(songData);
                await storeFileHandle(song.filePath, fileHandle);
                existingTitles.add(titleKey);
            }

            const folderMap = new Map();
            for (const song of songs) {
                const key = song.folderName?.trim() || 'My Music';
                if (!folderMap.has(key)) folderMap.set(key, []);
                folderMap.get(key).push(song.title);
            }
            for (const [folderName] of folderMap) {
                await db.playlists.add({
                    name: folderName, description: `Songs from folder: ${folderName}`,
                    emoji: '📁', isAutoGenerated: true, songIds: [], createdAt: new Date(),
                }).catch(() => {});
            }

            setPhase('done');
            await fetchSongs();
            await fetchPlaylists();
            setTimeout(() => onComplete(), 800);
        } catch (err) {
            if (err.name === 'AbortError') { setPhase('idle'); return; }
            setError(err.message || 'Something went wrong.');
            setPhase('error');
        }
    };

    return (
        <div style={{
            minHeight: '100vh',
            background: 'var(--bg-base, #07080f)',
            display: 'flex', flexDirection: 'column',
            alignItems: 'center', justifyContent: 'center',
            padding: '2rem', position: 'relative', overflow: 'hidden',
            fontFamily: 'var(--font, Inter, sans-serif)',
        }}>
            <style>{`
                @keyframes setup-spin     { to { transform: rotate(360deg); } }
                @keyframes setup-pulse    { 0%{ transform:scale(0.8); opacity:0.8 } 100%{ transform:scale(1.6); opacity:0 } }
                @keyframes setup-fade-up  { from { opacity: 0; transform: translateY(24px); } to { opacity: 1; transform: translateY(0); } }
                @keyframes setup-shine    { from { background-position: -200% center; } to { background-position: 200% center; } }
                @keyframes setup-eq       { 0%,100%{ height:6px } 50%{ height:22px } }
                .setup-anim { animation: setup-fade-up 0.5s ease-out both; }
                .setup-anim-d1 { animation: setup-fade-up 0.5s 0.1s ease-out both; }
                .setup-anim-d2 { animation: setup-fade-up 0.5s 0.2s ease-out both; }
                .setup-anim-d3 { animation: setup-fade-up 0.5s 0.3s ease-out both; }
            `}</style>

            {/* Background blobs */}
            <div style={{ position: 'absolute', top: '-15%', right: '-10%', width: 500, height: 500, borderRadius: '50%', background: 'radial-gradient(circle, rgba(124,58,237,0.12) 0%, transparent 70%)', filter: 'blur(60px)', pointerEvents: 'none' }} />
            <div style={{ position: 'absolute', bottom: '-15%', left: '-10%', width: 400, height: 400, borderRadius: '50%', background: 'radial-gradient(circle, rgba(236,72,153,0.08) 0%, transparent 70%)', filter: 'blur(60px)', pointerEvents: 'none' }} />

            {/* Card */}
            <div className="setup-anim" style={{ maxWidth: 520, width: '100%', background: 'rgba(22,27,39,0.8)', border: '1px solid var(--border, rgba(255,255,255,0.07))', borderRadius: 20, backdropFilter: 'blur(16px)', padding: '2.5rem 2rem', textAlign: 'center', position: 'relative' }}>

                {/* Icon */}
                <div style={{ position: 'relative', display: 'inline-block', marginBottom: '1.75rem' }}>
                    {phase === 'scanning' && (
                        <>
                            <div style={{ position: 'absolute', inset: -8, borderRadius: '50%', border: '2px solid rgba(124,58,237,0.5)', animation: 'setup-pulse 1.5s ease-out infinite' }} />
                            <div style={{ position: 'absolute', inset: -8, borderRadius: '50%', border: '2px solid rgba(124,58,237,0.3)', animation: 'setup-pulse 1.5s 0.5s ease-out infinite' }} />
                        </>
                    )}
                    <div style={{
                        width: 96, height: 96, borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center',
                        background: phase === 'done' ? 'linear-gradient(135deg, #22c55e, #15803d)' : 'linear-gradient(135deg, var(--accent, #7c3aed), #a78bfa)',
                        border: '3px solid rgba(255,255,255,0.12)',
                        animation: phase === 'scanning' ? 'setup-spin 2s linear infinite' : 'none',
                        transition: 'background 0.4s',
                        boxShadow: '0 0 40px rgba(124,58,237,0.3)',
                    }}>
                        {phase === 'done' ? <span style={{ fontSize: '2.5rem' }}>✓</span>
                            : phase === 'scanning' ? <Music2 size={40} color="#fff" />
                            : <FolderOpen size={40} color="#fff" />}
                    </div>
                </div>

                {/* Phase: IDLE / ERROR */}
                {(phase === 'idle' || phase === 'error') && (
                    <>
                        <h1 className="setup-anim-d1" style={{ fontSize: '1.2rem', fontWeight: 600, color: 'var(--text-muted, #94a3b8)', marginBottom: 4, letterSpacing: '0.08em', textTransform: 'uppercase' }}>Welcome to</h1>
                        <h2 className="setup-anim-d1" style={{ fontSize: 'clamp(2rem, 6vw, 3rem)', fontWeight: 900, letterSpacing: '-0.03em', marginBottom: '0.75rem' }}>
                            <span style={{ background: 'linear-gradient(135deg, var(--accent-light, #a78bfa), #ec4899)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>Smusic</span>
                        </h2>
                        <p className="setup-anim-d2" style={{ color: 'var(--text-muted, #94a3b8)', fontSize: '0.95rem', lineHeight: 1.6, marginBottom: '2rem' }}>
                            Your personal music collection, beautifully organized.<br />Select your music folder to get started.
                        </p>

                        {/* Feature pills */}
                        <div className="setup-anim-d2" style={{ display: 'flex', gap: '0.6rem', justifyContent: 'center', flexWrap: 'wrap', marginBottom: '2rem' }}>
                            {[
                                { icon: <Zap size={12} />, text: 'Auto-organized' },
                                { icon: <HardDrive size={12} />, text: 'Files stay local' },
                                { icon: <Shield size={12} />, text: 'No uploads needed' },
                            ].map(({ icon, text }) => (
                                <div key={text} style={{ display: 'flex', alignItems: 'center', gap: 5, padding: '4px 10px', borderRadius: 99, background: 'var(--accent-dim, rgba(124,58,237,0.18))', border: '1px solid rgba(124,58,237,0.3)', color: 'var(--accent-light, #a78bfa)', fontSize: '0.72rem', fontWeight: 600, letterSpacing: '0.04em' }}>
                                    {icon} {text}
                                </div>
                            ))}
                        </div>

                        {error && (
                            <div style={{ padding: '10px 14px', marginBottom: '1rem', background: 'rgba(239,68,68,0.12)', border: '1px solid rgba(239,68,68,0.3)', borderRadius: 10, color: '#fca5a5', fontSize: '0.85rem' }}>
                                {error}
                            </div>
                        )}

                        {isSupported ? (
                            <button className="setup-anim-d3"
                                onClick={handleSelectFolder}
                                style={{
                                    display: 'inline-flex', alignItems: 'center', gap: 10, padding: '0.9rem 2rem', background: 'var(--accent, #7c3aed)', border: 'none', borderRadius: 12, color: '#fff', cursor: 'pointer',
                                    fontSize: '1rem', fontWeight: 700, boxShadow: '0 8px 32px rgba(124,58,237,0.35)', transition: 'all 0.2s', width: '100%', justifyContent: 'center',
                                }}
                                onMouseEnter={e => { e.currentTarget.style.transform = 'translateY(-2px)'; e.currentTarget.style.boxShadow = '0 12px 40px rgba(124,58,237,0.45)'; }}
                                onMouseLeave={e => { e.currentTarget.style.transform = 'translateY(0)'; e.currentTarget.style.boxShadow = '0 8px 32px rgba(124,58,237,0.35)'; }}
                            >
                                <FolderOpen size={20} /> Select Music Folder
                            </button>
                        ) : (
                            <div style={{ padding: '1rem', background: 'rgba(245,158,11,0.12)', border: '1px solid rgba(245,158,11,0.3)', borderRadius: 10, color: 'var(--text-muted)', fontSize: '0.85rem' }}>
                                Folder scanning requires Chrome or Edge.<br />
                                <span style={{ fontSize: '0.78rem', opacity: 0.7 }}>Use the "+ Upload" option in Library instead.</span>
                            </div>
                        )}

                        <p className="setup-anim-d3" style={{ marginTop: '1.25rem', color: 'var(--text-subtle, #475569)', fontSize: '0.75rem' }}>
                            Works in Chrome & Edge · Files never leave your device
                        </p>
                    </>
                )}

                {/* Phase: SCANNING */}
                {phase === 'scanning' && (
                    <>
                        <h2 style={{ fontSize: '1.25rem', fontWeight: 800, marginBottom: '0.5rem' }}>Scanning Your Music</h2>
                        <p style={{ color: 'var(--text-muted)', marginBottom: '1.5rem' }}>
                            Found <strong style={{ color: 'var(--accent-light)', fontSize: '1.3rem' }}>{scanned}</strong> track{scanned !== 1 ? 's' : ''} so far…
                        </p>
                        <div style={{ display: 'flex', gap: 4, justifyContent: 'center', marginBottom: '1.25rem', alignItems: 'flex-end', height: 28 }}>
                            {[0, 0.15, 0.3, 0.45, 0.6, 0.75, 0.9].map((delay, i) => (
                                <div key={i} style={{ width: 5, borderRadius: 2, background: `hsl(${260 + i * 10}deg 70% 60%)`, animation: `setup-eq 0.8s ${delay}s ease-in-out infinite`, height: 6 }} />
                            ))}
                        </div>
                        <div style={{ height: 4, background: 'rgba(255,255,255,0.08)', borderRadius: 99, overflow: 'hidden', marginBottom: '0.875rem' }}>
                            <div style={{ height: '100%', background: 'linear-gradient(90deg, var(--accent), var(--accent-light))', backgroundSize: '200% auto', animation: 'setup-shine 1.5s linear infinite', width: '60%' }} />
                        </div>
                        {lastName && (
                            <p style={{ color: 'var(--text-subtle)', fontFamily: 'monospace', fontSize: '0.72rem', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', maxWidth: 360, margin: '0 auto' }}>{lastName}</p>
                        )}
                    </>
                )}

                {/* Phase: DONE */}
                {phase === 'done' && (
                    <>
                        <h2 style={{ fontSize: '1.5rem', fontWeight: 800, color: '#4ade80', marginBottom: '0.5rem' }}>Library Ready!</h2>
                        <p style={{ color: 'var(--text-muted)', fontSize: '0.95rem' }}>
                            Found <strong style={{ color: 'var(--accent-light)' }}>{scanned}</strong> tracks. Opening your collection…
                        </p>
                    </>
                )}
            </div>

            {/* Skip buttons */}
            {phase === 'idle' && (
                <button onClick={onComplete}
                    style={{ marginTop: '1.25rem', background: 'none', border: 'none', cursor: 'pointer', color: 'var(--text-subtle, #475569)', fontSize: '0.8rem', fontWeight: 500, textDecoration: 'underline', fontFamily: 'var(--font)' }}>
                    Skip for now →
                </button>
            )}
        </div>
    );
}
