import { useState } from 'react'
import { Plus, Play, Music, Heart, ChevronRight, ChevronLeft, Trash2, X, Pencil, Check, FolderOpen, Zap } from 'lucide-react'
import { useLibraryStore, usePlayerStore } from '../store/store.js'
import CreatePlaylistModal from '../components/playlists/CreatePlaylistModal'

function CoverArt({ song, size = 38 }) {
  const s = { width: size, height: size, borderRadius: 8, overflow: 'hidden', background: 'var(--bg-elevated)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, fontSize: size * 0.45 }
  if (song?.cover?.startsWith?.('http')) return <div style={s}><img src={song.cover} alt={song.title} style={{ width: '100%', height: '100%', objectFit: 'cover' }} /></div>
  return <div style={s}>{song?.cover || '🎵'}</div>
}

const ACCENT_COLORS = ['#7c3aed', '#0ea5e9', '#ec4899', '#22c55e', '#f59e0b', '#a78bfa']
const AUTO_COLORS   = ['#f59e0b', '#ea580c', '#ef4444', '#d946ef']

function PlaylistCard({ playlist, index, colorPool, songs, onSelect, onPlay }) {
  const psongs = (playlist.songIds || []).map(id => songs.find(s => s.id === id)).filter(Boolean)
  const color  = colorPool[index % colorPool.length]
  const isAuto = playlist.isAutoGenerated

  return (
    <div
      onClick={() => onSelect(playlist.id)}
      style={{ background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: 14, padding: '1rem', cursor: 'pointer', transition: 'border-color 0.15s, background 0.15s', position: 'relative', overflow: 'hidden' }}
      onMouseEnter={e => { e.currentTarget.style.background = 'var(--bg-card-hover)'; e.currentTarget.style.borderColor = color + '44'; }}
      onMouseLeave={e => { e.currentTarget.style.background = 'var(--bg-card)'; e.currentTarget.style.borderColor = 'var(--border)'; }}
    >
      {isAuto && (
        <span style={{ position: 'absolute', top: 8, right: 8, fontSize: '0.6rem', fontWeight: 700, letterSpacing: '0.08em', padding: '1px 6px', borderRadius: 4, background: color + '22', border: `1px solid ${color}44`, color }}
        >AUTO</span>
      )}
      <div style={{ display: 'flex', alignItems: 'center', gap: '0.875rem' }}>
        <div style={{ width: 48, height: 48, borderRadius: 10, background: color + '22', border: `1px solid ${color}44`, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, transition: 'transform 0.15s' }}>
          {isAuto ? <FolderOpen size={22} style={{ color }} /> : <span style={{ fontSize: '1.5rem' }}>{playlist.emoji}</span>}
        </div>
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ fontWeight: 700, fontSize: '0.95rem', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{playlist.name}</div>
          <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: 2 }}>{psongs.length} {psongs.length === 1 ? 'track' : 'tracks'}</div>
          {isAuto && <div style={{ fontSize: '0.68rem', color: 'var(--text-subtle)', fontStyle: 'italic' }}>From your music folder</div>}
        </div>
        <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 4 }}>
          <button
            onClick={e => { e.stopPropagation(); onPlay(playlist, e) }}
            className="btn-icon"
            style={{ background: color + '22', color, borderRadius: 8, padding: 6 }}
          ><Play size={14} /></button>
          <ChevronRight size={14} style={{ color: 'var(--text-subtle)' }} />
        </div>
      </div>
    </div>
  )
}

function Playlists() {
  const { playlists, songs, deletePlaylist, renamePlaylist, removeSongFromPlaylist, addSongsToPlaylist } = useLibraryStore()
  const { playSong, playWithQueue, currentSong, isPlaying, likedSongs } = usePlayerStore()
  const [showCreateModal, setShowCreateModal] = useState(false)
  const [selectedPlaylist, setSelectedPlaylist] = useState(null)
  const [showAddSongs, setShowAddSongs] = useState(false)
  const [isRenaming, setIsRenaming] = useState(false)
  const [renameDraft, setRenameDraft] = useState('')

  const autoPlaylists = playlists.filter(p => p.isAutoGenerated)
  const userPlaylists = playlists.filter(p => !p.isAutoGenerated)

  const getSongsForPlaylist = (pl) => (pl.songIds || []).map(id => songs.find(s => s.id === id)).filter(Boolean)

  const handlePlayPlaylist = (pl, e) => {
    if (e) e.stopPropagation()
    const ps = getSongsForPlaylist(pl)
    if (ps.length > 0) playWithQueue(ps[0], ps)
  }

  const likedSongsList = songs.filter(s => likedSongs.has(s.id))
  const handlePlayLiked = () => { if (likedSongsList.length > 0) playWithQueue(likedSongsList[0], likedSongsList) }

  // ═══════════════════════════════════════════════
  // DETAIL VIEW
  // ═══════════════════════════════════════════════
  if (selectedPlaylist) {
    const playlist = playlists.find(p => p.id === selectedPlaylist)
    if (!playlist) { setSelectedPlaylist(null); return null }

    const playlistSongs = getSongsForPlaylist(playlist)
    const available = songs.filter(s => !playlist.songIds.includes(s.id))
    const isAuto = playlist.isAutoGenerated

    return (
      <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }} className="animate-fade-up">
        <button className="btn-ghost" style={{ alignSelf: 'flex-start', fontSize: '0.82rem', padding: '0.4rem 0.875rem' }} onClick={() => { setSelectedPlaylist(null); setShowAddSongs(false) }}>
          <ChevronLeft size={16} /> Back
        </button>

        {/* Header */}
        <div style={{ background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: 16, padding: '1.5rem', display: 'flex', alignItems: 'center', gap: '1.25rem', flexWrap: 'wrap' }}>
          <div style={{ width: 64, height: 64, borderRadius: 12, background: 'var(--accent-dim)', border: '1px solid var(--border-accent)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, fontSize: '2rem' }}>
            {isAuto ? <FolderOpen size={28} style={{ color: 'var(--accent-light)' }} /> : playlist.emoji}
          </div>
          <div style={{ flex: 1, minWidth: 0 }}>
            {isAuto ? (
              <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                <h2 style={{ fontSize: '1.5rem', fontWeight: 800, letterSpacing: '-0.03em' }}>{playlist.name}</h2>
                <span style={{ fontSize: '0.6rem', fontWeight: 700, letterSpacing: '0.08em', padding: '2px 8px', borderRadius: 4, background: 'var(--accent-dim)', border: '1px solid var(--border-accent)', color: 'var(--accent-light)' }}>AUTO</span>
              </div>
            ) : isRenaming ? (
              <div style={{ display: 'flex', gap: 6, alignItems: 'center' }}>
                <input type="text" value={renameDraft} onChange={e => setRenameDraft(e.target.value)}
                  onKeyDown={e => { if (e.key === 'Enter' && renameDraft.trim()) { renamePlaylist(playlist.id, renameDraft.trim()); setIsRenaming(false) } else if (e.key === 'Escape') setIsRenaming(false) }}
                  className="s-input" style={{ fontSize: '1.1rem', fontWeight: 700, padding: '0.3rem 0.6rem', width: 'auto' }} autoFocus
                />
                <button className="btn-icon" onClick={() => { if (renameDraft.trim()) { renamePlaylist(playlist.id, renameDraft.trim()); setIsRenaming(false) } }} style={{ color: 'var(--success)' }}><Check size={18} /></button>
                <button className="btn-icon" onClick={() => setIsRenaming(false)}><X size={16} /></button>
              </div>
            ) : (
              <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                <h2 style={{ fontSize: '1.5rem', fontWeight: 800 }}>{playlist.name}</h2>
                <button className="btn-icon" onClick={() => { setRenameDraft(playlist.name); setIsRenaming(true) }}><Pencil size={15} /></button>
              </div>
            )}
            {playlist.description && <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginTop: 4, fontStyle: 'italic' }}>{playlist.description}</p>}
            <p style={{ fontSize: '0.78rem', color: 'var(--text-subtle)', marginTop: 4 }}>
              {playlistSongs.length} {playlistSongs.length === 1 ? 'track' : 'tracks'}
              {isAuto && <span style={{ marginLeft: 8 }}>· Updated on re-scan</span>}
            </p>
          </div>
          <div style={{ display: 'flex', gap: 8 }}>
            {playlistSongs.length > 0 && <button className="btn-accent" style={{ fontSize: '0.82rem' }} onClick={() => handlePlayPlaylist(playlist)}><Play size={15} /> Play All</button>}
            <button className="btn-icon" style={{ color: 'var(--text-subtle)' }} onClick={() => { deletePlaylist(playlist.id); setSelectedPlaylist(null) }} onMouseEnter={e => e.currentTarget.style.color = '#ef4444'} onMouseLeave={e => e.currentTarget.style.color = 'var(--text-subtle)'}><Trash2 size={18} /></button>
          </div>
        </div>

        {/* Auto info */}
        {isAuto && (
          <div style={{ display: 'flex', gap: 10, padding: '10px 14px', background: 'var(--accent-dim)', border: '1px solid var(--border-accent)', borderRadius: 10, fontSize: '0.78rem', color: 'var(--text-muted)', lineHeight: 1.5, alignItems: 'flex-start' }}>
            <FolderOpen size={15} style={{ flexShrink: 0, marginTop: 2, color: 'var(--accent-light)' }} />
            <span>Removing a song here only removes it from this playlist view — the original file is not deleted. Re-scanning will re-add removed songs.</span>
          </div>
        )}

        {/* Track list */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
          {playlistSongs.map((song, idx) => {
            const active = currentSong?.id === song.id && isPlaying
            return (
              <div key={song.id} onClick={() => playWithQueue(song, playlistSongs)}
                style={{ display: 'flex', alignItems: 'center', gap: '0.875rem', padding: '0.55rem 0.75rem', borderRadius: 10, cursor: 'pointer', background: active ? 'rgba(124,58,237,0.1)' : 'transparent', transition: 'background 0.12s' }}
                onMouseEnter={e => { if (!active) e.currentTarget.style.background = 'rgba(255,255,255,0.04)' }}
                onMouseLeave={e => { if (!active) e.currentTarget.style.background = 'transparent' }}>
                <span style={{ width: 22, textAlign: 'center', fontSize: '0.7rem', color: active ? 'var(--accent-light)' : 'var(--text-subtle)', fontWeight: 600 }}>
                  {active ? <span style={{ display: 'inline-flex', alignItems: 'flex-end', gap: 2, height: 10 }}><span className="eq-bar"/><span className="eq-bar"/></span> : String(idx+1).padStart(2,'0')}
                </span>
                <CoverArt song={song} size={36} />
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{ fontWeight: 600, fontSize: '0.85rem', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', color: active ? 'var(--accent-light)' : 'var(--text-primary)' }}>{song.title}</div>
                  <div style={{ fontSize: '0.72rem', color: 'var(--text-muted)' }}>{song.artist}{song.album ? ` · ${song.album}` : ''}</div>
                </div>
                <span style={{ fontSize: '0.72rem', color: 'var(--text-subtle)' }}>{song.duration}</span>
                <button className="btn-icon" onClick={e => { e.stopPropagation(); removeSongFromPlaylist(playlist.id, song.id) }} style={{ color: 'var(--text-subtle)' }} onMouseEnter={e => e.currentTarget.style.color = '#ef4444'} onMouseLeave={e => e.currentTarget.style.color = 'var(--text-subtle)'}><X size={15} /></button>
                <button className="btn-icon" onClick={e => { e.stopPropagation(); playWithQueue(song, playlistSongs) }} style={{ background: 'var(--accent-dim)', color: 'var(--accent-light)', borderRadius: 8 }}><Play size={14} /></button>
              </div>
            )
          })}
          {playlistSongs.length === 0 && (
            <div style={{ textAlign: 'center', padding: '3rem 1rem' }}>
              <div style={{ fontSize: '3rem', marginBottom: '0.75rem' }}>{isAuto ? '📁' : '🎵'}</div>
              <p style={{ fontWeight: 700, marginBottom: 4 }}>No tracks yet</p>
              <p style={{ color: 'var(--text-muted)', fontSize: '0.82rem' }}>{isAuto ? 'Run a Re-Scan from the Library page.' : 'Add songs to get started.'}</p>
            </div>
          )}
        </div>

        {/* Add songs */}
        <div>
          <button className="btn-ghost" onClick={() => setShowAddSongs(!showAddSongs)} style={{ fontSize: '0.82rem' }}><Plus size={15} /> {showAddSongs ? 'Hide Songs' : 'Add Songs'}</button>
          {showAddSongs && (
            <div className="animate-fade-in" style={{ marginTop: '1rem', display: 'flex', flexDirection: 'column', gap: 2 }}>
              <p className="section-title" style={{ marginBottom: 8 }}>Available Songs ({available.length})</p>
              {available.map(song => (
                <div key={song.id} onClick={() => addSongsToPlaylist(playlist.id, [song.id])}
                  style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', padding: '0.5rem 0.75rem', borderRadius: 8, cursor: 'pointer', border: '1px solid var(--border)', transition: 'border-color 0.12s, background 0.12s' }}
                  onMouseEnter={e => { e.currentTarget.style.borderColor = 'var(--border-accent)'; e.currentTarget.style.background = 'rgba(255,255,255,0.03)' }}
                  onMouseLeave={e => { e.currentTarget.style.borderColor = 'var(--border)'; e.currentTarget.style.background = 'transparent' }}>
                  <CoverArt song={song} size={32} />
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <div style={{ fontWeight: 600, fontSize: '0.82rem', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{song.title}</div>
                    <div style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>{song.artist}</div>
                  </div>
                  <span style={{ fontSize: '0.7rem', color: 'var(--text-subtle)' }}>{song.duration}</span>
                  <button className="btn-icon" style={{ background: 'var(--accent-dim)', color: 'var(--accent-light)', borderRadius: 6 }}><Plus size={14} /></button>
                </div>
              ))}
              {available.length === 0 && <p style={{ fontSize: '0.82rem', color: 'var(--text-subtle)', textAlign: 'center', padding: '1rem' }}>All songs already in this playlist!</p>}
            </div>
          )}
        </div>
      </div>
    )
  }

  // ═══════════════════════════════════════════════
  // GRID VIEW
  // ═══════════════════════════════════════════════
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}>
      {/* Header */}
      <div className="animate-fade-up" style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: '1rem', flexWrap: 'wrap' }}>
        <div>
          <h1 style={{ fontSize: 'clamp(1.5rem, 4vw, 2rem)', fontWeight: 900, letterSpacing: '-0.03em' }}>Collections</h1>
          <p style={{ color: 'var(--text-muted)', fontSize: '0.85rem', marginTop: 4 }}>{autoPlaylists.length + userPlaylists.length} playlists</p>
        </div>
        <button className="btn-accent" onClick={() => setShowCreateModal(true)} style={{ fontSize: '0.82rem' }}><Plus size={16} /> New Playlist</button>
      </div>

      {/* Liked songs */}
      <div className="animate-fade-up delay-1"
        onClick={handlePlayLiked}
        style={{ background: 'linear-gradient(135deg, rgba(244,63,94,0.15), rgba(236,72,153,0.1))', border: '1px solid rgba(244,63,94,0.25)', borderRadius: 14, padding: '1rem 1.25rem', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '1rem', transition: 'border-color 0.15s' }}
        onMouseEnter={e => e.currentTarget.style.borderColor = 'rgba(244,63,94,0.5)'}
        onMouseLeave={e => e.currentTarget.style.borderColor = 'rgba(244,63,94,0.25)'}
      >
        <div style={{ width: 44, height: 44, borderRadius: 10, background: 'rgba(244,63,94,0.2)', border: '1px solid rgba(244,63,94,0.35)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
          <Heart size={20} fill="#f43f5e" color="#f43f5e" />
        </div>
        <div style={{ flex: 1 }}>
          <div style={{ fontWeight: 700, fontSize: '1rem' }}>Liked Songs</div>
          <div style={{ fontSize: '0.78rem', color: 'var(--text-muted)' }}>{likedSongsList.length} tracks · Your favorites</div>
        </div>
        <button className="btn-icon" style={{ background: 'rgba(244,63,94,0.2)', color: '#f43f5e', borderRadius: 8, padding: 8 }} onClick={e => { e.stopPropagation(); handlePlayLiked() }}><Play size={16} /></button>
      </div>

      {/* Auto playlists */}
      {autoPlaylists.length > 0 && (
        <section className="animate-fade-up delay-2">
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: '0.875rem' }}>
            <FolderOpen size={16} style={{ color: 'var(--accent-light)' }} />
            <p className="section-title">From Your Folders</p>
            <span style={{ fontSize: '0.68rem', color: 'var(--text-subtle)', fontStyle: 'italic' }}>{autoPlaylists.length} folders</span>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: '0.75rem' }}>
            {autoPlaylists.map((pl, i) => <PlaylistCard key={pl.id} playlist={pl} index={i} colorPool={AUTO_COLORS} songs={songs} onSelect={setSelectedPlaylist} onPlay={handlePlayPlaylist} />)}
          </div>
        </section>
      )}

      {/* User playlists */}
      {userPlaylists.length > 0 && (
        <section className="animate-fade-up delay-3">
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: '0.875rem' }}>
            <Zap size={16} style={{ color: 'var(--accent-light)' }} />
            <p className="section-title">Your Playlists</p>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: '0.75rem' }}>
            {userPlaylists.map((pl, i) => <PlaylistCard key={pl.id} playlist={pl} index={i} colorPool={ACCENT_COLORS} songs={songs} onSelect={setSelectedPlaylist} onPlay={handlePlayPlaylist} />)}
          </div>
        </section>
      )}

      {/* Create card */}
      <div className="animate-fade-up delay-4"
        onClick={() => setShowCreateModal(true)}
        style={{ border: '1px dashed rgba(255,255,255,0.12)', borderRadius: 14, padding: '2rem', textAlign: 'center', cursor: 'pointer', transition: 'border-color 0.15s, background 0.15s' }}
        onMouseEnter={e => { e.currentTarget.style.borderColor = 'var(--border-accent)'; e.currentTarget.style.background = 'rgba(124,58,237,0.05)' }}
        onMouseLeave={e => { e.currentTarget.style.borderColor = 'rgba(255,255,255,0.12)'; e.currentTarget.style.background = 'transparent' }}>
        <div style={{ width: 42, height: 42, borderRadius: 10, background: 'var(--accent-dim)', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 0.75rem' }}>
          <Plus size={20} style={{ color: 'var(--accent-light)' }} />
        </div>
        <p style={{ fontWeight: 600, fontSize: '0.9rem', marginBottom: 4 }}>Create Playlist</p>
        <p style={{ fontSize: '0.75rem', color: 'var(--text-subtle)' }}>Organize your music</p>
      </div>

      {showCreateModal && <CreatePlaylistModal onClose={() => setShowCreateModal(false)} />}
    </div>
  )
}

export default Playlists
